// Generated by gencpp from file coorsa_rfsm/fsm_event.msg
// DO NOT EDIT!


#ifndef COORSA_RFSM_MESSAGE_FSM_EVENT_H
#define COORSA_RFSM_MESSAGE_FSM_EVENT_H

#include <ros/service_traits.h>


#include <coorsa_rfsm/fsm_eventRequest.h>
#include <coorsa_rfsm/fsm_eventResponse.h>


namespace coorsa_rfsm
{

struct fsm_event
{

typedef fsm_eventRequest Request;
typedef fsm_eventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fsm_event
} // namespace coorsa_rfsm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::coorsa_rfsm::fsm_event > {
  static const char* value()
  {
    return "6aea470b1ed54075e83032ee4be16538";
  }

  static const char* value(const ::coorsa_rfsm::fsm_event&) { return value(); }
};

template<>
struct DataType< ::coorsa_rfsm::fsm_event > {
  static const char* value()
  {
    return "coorsa_rfsm/fsm_event";
  }

  static const char* value(const ::coorsa_rfsm::fsm_event&) { return value(); }
};


// service_traits::MD5Sum< ::coorsa_rfsm::fsm_eventRequest> should match
// service_traits::MD5Sum< ::coorsa_rfsm::fsm_event >
template<>
struct MD5Sum< ::coorsa_rfsm::fsm_eventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::coorsa_rfsm::fsm_event >::value();
  }
  static const char* value(const ::coorsa_rfsm::fsm_eventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::coorsa_rfsm::fsm_eventRequest> should match
// service_traits::DataType< ::coorsa_rfsm::fsm_event >
template<>
struct DataType< ::coorsa_rfsm::fsm_eventRequest>
{
  static const char* value()
  {
    return DataType< ::coorsa_rfsm::fsm_event >::value();
  }
  static const char* value(const ::coorsa_rfsm::fsm_eventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::coorsa_rfsm::fsm_eventResponse> should match
// service_traits::MD5Sum< ::coorsa_rfsm::fsm_event >
template<>
struct MD5Sum< ::coorsa_rfsm::fsm_eventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::coorsa_rfsm::fsm_event >::value();
  }
  static const char* value(const ::coorsa_rfsm::fsm_eventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::coorsa_rfsm::fsm_eventResponse> should match
// service_traits::DataType< ::coorsa_rfsm::fsm_event >
template<>
struct DataType< ::coorsa_rfsm::fsm_eventResponse>
{
  static const char* value()
  {
    return DataType< ::coorsa_rfsm::fsm_event >::value();
  }
  static const char* value(const ::coorsa_rfsm::fsm_eventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COORSA_RFSM_MESSAGE_FSM_EVENT_H
