// Generated by gencpp from file coorsa_rfsm/fsm_eventResponse.msg
// DO NOT EDIT!


#ifndef COORSA_RFSM_MESSAGE_FSM_EVENTRESPONSE_H
#define COORSA_RFSM_MESSAGE_FSM_EVENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coorsa_rfsm
{
template <class ContainerAllocator>
struct fsm_eventResponse_
{
  typedef fsm_eventResponse_<ContainerAllocator> Type;

  fsm_eventResponse_()
    {
    }
  fsm_eventResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> const> ConstPtr;

}; // struct fsm_eventResponse_

typedef ::coorsa_rfsm::fsm_eventResponse_<std::allocator<void> > fsm_eventResponse;

typedef boost::shared_ptr< ::coorsa_rfsm::fsm_eventResponse > fsm_eventResponsePtr;
typedef boost::shared_ptr< ::coorsa_rfsm::fsm_eventResponse const> fsm_eventResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace coorsa_rfsm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coorsa_rfsm/fsm_eventResponse";
  }

  static const char* value(const ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fsm_eventResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::coorsa_rfsm::fsm_eventResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COORSA_RFSM_MESSAGE_FSM_EVENTRESPONSE_H
