// Generated by gencpp from file coorsa_rfsm/fsm_eventRequest.msg
// DO NOT EDIT!


#ifndef COORSA_RFSM_MESSAGE_FSM_EVENTREQUEST_H
#define COORSA_RFSM_MESSAGE_FSM_EVENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coorsa_rfsm
{
template <class ContainerAllocator>
struct fsm_eventRequest_
{
  typedef fsm_eventRequest_<ContainerAllocator> Type;

  fsm_eventRequest_()
    : event()  {
    }
  fsm_eventRequest_(const ContainerAllocator& _alloc)
    : event(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type;
  _event_type event;





  typedef boost::shared_ptr< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> const> ConstPtr;

}; // struct fsm_eventRequest_

typedef ::coorsa_rfsm::fsm_eventRequest_<std::allocator<void> > fsm_eventRequest;

typedef boost::shared_ptr< ::coorsa_rfsm::fsm_eventRequest > fsm_eventRequestPtr;
typedef boost::shared_ptr< ::coorsa_rfsm::fsm_eventRequest const> fsm_eventRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator1> & lhs, const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator2> & rhs)
{
  return lhs.event == rhs.event;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator1> & lhs, const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coorsa_rfsm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aea470b1ed54075e83032ee4be16538";
  }

  static const char* value(const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aea470b1ed54075ULL;
  static const uint64_t static_value2 = 0xe83032ee4be16538ULL;
};

template<class ContainerAllocator>
struct DataType< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coorsa_rfsm/fsm_eventRequest";
  }

  static const char* value(const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string event\n"
;
  }

  static const char* value(const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fsm_eventRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coorsa_rfsm::fsm_eventRequest_<ContainerAllocator>& v)
  {
    s << indent << "event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COORSA_RFSM_MESSAGE_FSM_EVENTREQUEST_H
